reduce password prompts

diff --git a/browserscript b/browserscript
--- a/browserscript
+++ b/browserscript
@@ -17,7 +17,11 @@ secure_repo_files() {
     echo "Securing the repo files against manipulation. Please enter your password one last time."
     run0 sh -c "chown root:root /etc/yum.repos.d/* && \
                    chmod 744 /etc/yum.repos.d/* && \
-                   chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/" || { echo "Failed to secure the repo files!"; exit 1; }
+                   chcon -R system_u:object_r:system_conf_t:s0 /etc/yum.repos.d/
+                " || {
+        echo "Failed to secure the repo files!"
+        exit 1
+    }
     echo
 }
 
@@ -31,9 +35,9 @@ enabled=1
 gpgcheck=1
 gpgkey=https://repo.vivaldi.com/archive/linux_signing_key.pub
 EOF"
-    echo "Vivaldi ($arch) Repo added" &&\
-    secure_repo_files &&\
-    echo "installing..."
+    echo "Vivaldi ($arch) Repo added" &&
+        secure_repo_files &&
+        echo "installing..."
 }
 
 # User input for Brave version
@@ -58,60 +62,88 @@ echo
 # Determine repository URL and GPG key based on user's choice
 
 case "$browser_choice" in
-    1)
-        echo "Downloading Repo and Key, you need to enter a password."
-        curl -LsS $BRAVE_BASEURL/brave-browser.repo -o /tmp/brave-browser.repo || { echo "Failed to download Brave repo."; exit 1; }
-        run0 mv /tmp/brave-browser.repo /etc/yum.repos.d/brave-browser.repo
-        curl -LsS $BRAVE_BASEURL/brave-core.asc -o /tmp/brave-core.asc || { echo "Failed to download Brave key"; exit 1; }
-        run0 mv /tmp/brave-core.asc /etc/pki/rpm-gpg/brave-core.asc
-        echo "Brave Repo and Key downloaded." &&\
-        secure_repo_files &&\
-        echo "Installing..." &&\
+1)
+    echo "Downloading Repo and Key, you need to enter a password."
+    curl -LsS $BRAVE_BASEURL/brave-browser.repo -o /tmp/brave-browser.repo || {
+        echo "Failed to download Brave repo."
+        exit 1
+    }
+    curl -LsS $BRAVE_BASEURL/brave-core.asc -o /tmp/brave-core.asc || {
+        echo "Failed to download Brave key"
+        exit 1
+    }
+    run0 sh -c '
+        mv /tmp/brave-browser.repo /etc/yum.repos.d/brave-browser.repo
+        mv /tmp/brave-core.asc /etc/pki/rpm-gpg/brave-core.asc
+    '
+    echo "Brave Repo and Key downloaded." &&
+        secure_repo_files &&
+        echo "Installing..." &&
         rpm-ostree install brave-browser
-        ;;
+    ;;
 
-    2)
-        echo "Downloading Repo and Key, you need to enter a password."
-        curl -LsS $BRAVE_BASEURL_BETA/brave-browser-beta.repo -o /tmp/brave-browser-beta.repo || { echo "Failed to download Brave repo."; exit 1; }
-        run0 mv /tmp/brave-browser-beta.repo /etc/yum.repos.d/brave-browser-beta.repo
-        curl -LsS $BRAVE_BASEURL_BETA/brave-core-nightly.asc -o /tmp/brave-core-nightly.asc || { echo "Failed to download Brave key."; exit 1; }
-        run0 mv /tmp/brave-core-nightly.asc /etc/pki/rpm-gpg/brave-core-nightly.asc
-        echo "Brave Repo and Key downloaded." &&\
-        secure_repo_files &&\
-        echo "Installing..." &&\
+2)
+    echo "Downloading Repo and Key, you need to enter a password."
+    curl -LsS $BRAVE_BASEURL_BETA/brave-browser-beta.repo -o /tmp/brave-browser-beta.repo || {
+        echo "Failed to download Brave repo."
+        exit 1
+    }
+    curl -LsS $BRAVE_BASEURL_BETA/brave-core-nightly.asc -o /tmp/brave-core-nightly.asc || {
+        echo "Failed to download Brave key."
+        exit 1
+    }
+    run0 sh -c '
+        mv /tmp/brave-browser-beta.repo /etc/yum.repos.d/brave-browser-beta.repo
+        mv /tmp/brave-core-nightly.asc /etc/pki/rpm-gpg/brave-core-nightly.asc
+    '
+    echo "Brave Repo and Key downloaded." &&
+        secure_repo_files &&
+        echo "Installing..." &&
         rpm-ostree install brave-browser-beta
-        ;;
+    ;;
 
-    3)
-        echo "Downloading Repo and Key, you need to enter a password."
-        curl -LsS $BRAVE_BASEURL_NIGHTLY/brave-browser-nightly.repo -o /tmp/brave-browser-nightly.repo || { echo "Failed to download Brave repo."; exit 1; }
-        run0 mv /tmp/brave-browser-nightly.repo /etc/yum.repos.d/brave-browser-nightly.repo
-        curl -LsS $BRAVE_BASEURL_NIGHTLY/brave-core-nightly.asc -o /tmp/brave-core-nightly.asc || { echo "Failed to download Brave key"; exit 1; }
-        run0 mv /tmp/brave-core-nightly.asc /etc/pki/rpm-gpg/brave-core-nightly.asc
-        echo "Brave Repo and Key downloaded." &&\
-        secure_repo_files &&\
-        echo "Installing..." &&\
+3)
+    echo "Downloading Repo and Key, you need to enter a password."
+    curl -LsS $BRAVE_BASEURL_NIGHTLY/brave-browser-nightly.repo -o /tmp/brave-browser-nightly.repo || {
+        echo "Failed to download Brave repo."
+        exit 1
+    }
+    curl -LsS $BRAVE_BASEURL_NIGHTLY/brave-core-nightly.asc -o /tmp/brave-core-nightly.asc || {
+        echo "Failed to download Brave key"
+        exit 1
+    }
+    run0 sh -c '
+        mv /tmp/brave-browser-nightly.repo /etc/yum.repos.d/brave-browser-nightly.repo
+        mv /tmp/brave-core-nightly.asc /etc/pki/rpm-gpg/brave-core-nightly.asc
+    '
+    echo "Brave Repo and Key downloaded." &&
+        secure_repo_files &&
+        echo "Installing..." &&
         rpm-ostree install brave-browser-nightly
-        ;;
+    ;;
 
-    4)
-        add_vivaldi_repo "x86_64" &&\
-        rpm-ostree install vivaldi-stable ;;
+4)
+    add_vivaldi_repo "x86_64" &&
+        rpm-ostree install vivaldi-stable
+    ;;
 
-    5)
-        add_vivaldi_repo "aarch64" &&\
-        rpm-ostree install vivaldi-stable ;;
+5)
+    add_vivaldi_repo "aarch64" &&
+        rpm-ostree install vivaldi-stable
+    ;;
 
-    6)
-        add_vivaldi_repo "x86_64" &&\
-        rpm-ostree install vivaldi-snapshot ;;
+6)
+    add_vivaldi_repo "x86_64" &&
+        rpm-ostree install vivaldi-snapshot
+    ;;
 
-    7)
-        add_vivaldi_repo "aarch64" &&\
-        rpm-ostree install vivaldi-snapshot ;;
+7)
+    add_vivaldi_repo "aarch64" &&
+        rpm-ostree install vivaldi-snapshot
+    ;;
 
-    *)
-        echo "Invalid choice. You can use 'CTRL+c' to exit." &&\
+*)
+    echo "Invalid choice. You can use 'CTRL+c' to exit." &&
         read -r -p "Which Browser do you want to install? (1-7): " browser_choice
-        ;;
+    ;;
 esac
